### ISSUE TITLE
topological-sort DAG exception

### ISSUE THREAD

**Issue by AndreyGeonya** [mgechev/javascript-algorithms#7]
What wrong with my code? I have an exception "The graph is not a DAG".

    var topsort = require('../src/graphs/others/topological-sort').topologicalSort;
    var graph = [[0, 1, 0, 0, 1],
                 [0, 0, 0, 0, 0],
                 [1, 1, 0, 1, 1],
                 [0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0]];
    var vertices = topsort(graph);

But there is a graph I want to represent: 
![image001](https://cloud.githubusercontent.com/assets/773648/5672697/964ae8cc-979b-11e4-891d-5680e7ceca5b.png)

and it looks directed and acyclic.

**Comment by mgechev** [comment]
This implementation of the topological sort algorithm accepts graph represented as a list of neighbors.
This means that the invocation, corresponding to your adjust, matrix should look like:

```javascript
var graph = {};
graph.G1 = ['G2', 'G5'];
graph.G2 = [];
graph.G3 = ['G1', 'G2', 'G4', 'G5'];
graph.G4 = [];
graph.G5 = [];

console.log(topologicalSort(graph));
// ['G3', 'G4', 'G1', 'G5', 'G2']
```
The graph, which corresponds to your adjust matrix should look differently (since A[i][j] = 1, (i, j) ϵ E), more like this:

![](http://s9.postimg.org/49pxh8b67/graph.png)

As comment I'll add that the required representation of this algorithm is list of neighbors.
